import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/theme/provider";
import { Toaster } from "@/components/ui/sonner";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "./convex/providers";
import ReduxProvider from "@/redux/provider";
import { ConvexUserRaw, normalizeProfile } from "@/types/user";
import { ProfileQuery } from "@/convex/query.config";
import { preloadedQueryResult } from "convex/nextjs";

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Bareform",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rawProfile = await ProfileQuery();
  const user = preloadedQueryResult(rawProfile);
  const profile = normalizeProfile(user as ConvexUserRaw | null);

  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${outfit.className} antialiased`}>
        <ConvexAuthNextjsServerProvider>
          <ConvexClientProvider>
            <ThemeProvider>
              <ReduxProvider preloadedState={{ profile }}>
                {children}
                <Toaster />
              </ReduxProvider>
            </ThemeProvider>
          </ConvexClientProvider>
        </ConvexAuthNextjsServerProvider>
      </body>
    </html>
  );
}
